export const data = [
  { id: "0", image: require("../../assets/1a.jpg"), name: "Burgers" },
  { id: "1", image: require("../../assets/2a.jpg"), name: "Pizza" },
  { id: "2", image: require("../../assets/4a.jpg"), name: "Fries" },
  { id: "3", image: require("../../assets/3.jpg"), name: "Leg" },
  { id: "4", image: require("../../assets/3a.jpg"), name: "Fish" },
  { id: "5", image: require("../../assets/7a.jpg"), name: "Quorma" },
  { id: "6", image: require("../../assets/5a.jpg"), name: "Swarma" },
  { id: "7", image: require("../../assets/5.jpg"), name: "Pratha" },
  { id: "8", image: require("../../assets/6.jpg"), name: "Nihari" },
];
export const data1 = [
  { id: "0", image: require("../../assets/1.jpg"), name: "Chinees" },
  {
    id: "1",
    image: require("../../assets/2.jpg"),
    name: "Finger Fries",
  },
  { id: "2", image: require("../../assets/4a.jpg"), name: "Fries" },
  { id: "3", image: require("../../assets/3.jpg"), name: "Leg" },
  { id: "4", image: require("../../assets/3a.jpg"), name: "Fish" },
  { id: "5", image: require("../../assets/7a.jpg"), name: "Half Fried Chips" },
  { id: "6", image: require("../../assets/4.jpg"), name: "Italic" },
  { id: "7", image: require("../../assets/5.jpg"), name: "Chicken Pratha" },
  { id: "8", image: require("../../assets/5a.jpg"), name: "Swarma" },
];

export const foodCardData = [
  {
    RestName: "Al Madina",
    faraway: "12.4",
    BussinessAddress: "Sher Shah Colony",
    image: require("../../assets/3.jpg"),
    AvrgReview: 4.9,
    NoOfReview: 270,
    cordinates: { lat: 20.342, Long: 12.432 },
    Discount: 10,
    DeliveryTime: 15,
    CollectTime: 5,
    FoodType: "Burger, Wrap and MilkShake",
    ProductData: [
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2.jpg"),
      },
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
    ],
    id: 0,
  },
  {
    RestName: "Al Madina",
    faraway: "12.4",
    BussinessAddress: "Sher Shah Colony",
    image: require("../../assets/2.jpg"),
    AvrgReview: 4.9,
    NoOfReview: 270,
    cordinates: { lat: 20.342, Long: 12.432 },
    Discount: 10,
    DeliveryTime: 15,
    CollectTime: 5,
    FoodType: "Burger, Wrap and MilkShake",
    ProductData: [
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
    ],
    id: 1,
  },
  {
    RestName: "Al Madina",
    faraway: "12.4",
    BussinessAddress: "Sher Shah Colony",
    image: require("../../assets/1.jpg"),
    AvrgReview: 4.9,
    NoOfReview: 270,
    cordinates: { lat: 20.342, Long: 12.432 },
    Discount: 10,
    DeliveryTime: 15,
    CollectTime: 5,
    FoodType: "Burger, Wrap and MilkShake",
    ProductData: [
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
    ],
    id: 2,
  },
  {
    RestName: "Al Madina",
    faraway: "12.4",
    BussinessAddress: "Sher Shah Colony",
    image: require("../../assets/4.jpg"),
    AvrgReview: 4.9,
    NoOfReview: 270,
    cordinates: { lat: 20.342, Long: 12.432 },
    Discount: 10,
    DeliveryTime: 15,
    CollectTime: 5,
    FoodType: "Burger, Wrap and MilkShake",
    ProductData: [
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
    ],
    id: 3,
  },
  {
    RestName: "Al Madina",
    faraway: "12.4",
    BussinessAddress: "Sher Shah Colony",
    image: require("../../assets/5.jpg"),
    AvrgReview: 4.9,
    NoOfReview: 270,
    cordinates: { lat: 20.342, Long: 12.432 },
    Discount: 10,
    DeliveryTime: 15,
    CollectTime: 5,
    FoodType: "Burger, Wrap and MilkShake",
    ProductData: [
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
    ],
    id: 4,
  },
  {
    RestName: "Al Madina",
    faraway: "12.4",
    BussinessAddress: "Sher Shah Colony",
    image: require("../../assets/6.jpg"),
    AvrgReview: 4.9,
    NoOfReview: 270,
    cordinates: { lat: 20.342, Long: 12.432 },
    Discount: 10,
    DeliveryTime: 15,
    CollectTime: 5,
    FoodType: "Burger, Wrap and MilkShake",
    ProductData: [
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
    ],
    id: 5,
  },
  {
    RestName: "Al Madina",
    faraway: "12.4",
    BussinessAddress: "Sher Shah Colony",
    image: require("../../assets/5.jpg"),
    AvrgReview: 4.9,
    NoOfReview: 270,
    cordinates: { lat: 20.342, Long: 12.432 },
    Discount: 10,
    DeliveryTime: 15,
    CollectTime: 5,
    FoodType: "Burger, Wrap and MilkShake",
    ProductData: [
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
      {
        Name: "Hand Cut Chips",
        price: 99.99,
        image: require("../../assets/2a.jpg"),
      },
    ],
    id: 6,
  },
];

export const restaurantsData = [
  {
    restaurantName: "Mc Donalds",
    farAway: "21.2",
    businessAddress: "22 Bessie street, Cape Town",
    images: require("../../assets/1.jpg"),
    averageReview: 4.9,
    numberOfReview: 272,
    coordinates: { lat: -26.1888612, lng: 28.246325 },
    discount: 10,
    deliveryTime: 15,
    collectTime: 5,
    foodType: "Burgers, Wraps,Milkshakes...",
    productData: [
      {
        name: "Hand cut chips",
        price: 29.3,
        image: require("../../assets/1.jpg"),
      },
      { name: "Big Mac", price: 50.8, image: require("../../assets/1.jpg") },
    ],
    id: 0,
  },
  {
    restaurantName: "KFC",
    farAway: "12.7",
    businessAddress: "22 Bessie street, Cape Town",
    images: require("../../assets/2.jpg"),
    averageReview: 4.3,
    numberOfReview: 306,
    coordinates: { lat: -26.1891648, lng: 28.2441808 },
    discount: 20,
    deliveryTime: 30,
    collectTime: 10,
    foodType: "Chicken,Chicken wings...",
    productData: [
      {
        name: "Hand cut chips",
        price: 29.3,
        image: require("../../assets/2.jpg"),
      },
      { name: "Big Mac", price: 50.8, image: require("../../assets/2.jpg") },
      {
        name: "Chicken Burger",
        price: 70,
        image: require("../../assets/3.jpg"),
      },
    ],
    id: 1,
  },
  {
    restaurantName: "Steers",
    farAway: "5",
    businessAddress: "17 Olivia Rd, Johannesburg",
    images: require("../../assets/3.jpg"),
    coordinates: { lat: -26.1886781, lng: 28.244879 },
    averageReview: 4.9,
    numberOfReview: 1272,
    discount: 12,
    deliveryTime: 25,
    collectTime: 15,
    foodType: "Flame grilled beef Burgers",
    productData: [
      {
        name: "Hand cut chips",
        price: 29.3,
        image: require("../../assets/3.jpg"),
      },
      { name: "Big Mac", price: 50.8, image: require("../../assets/3.jpg") },
      {
        name: "Chicken Burger",
        price: 70,
        image: require("../../assets/3.jpg"),
      },
    ],
    id: 2,
  },
  {
    restaurantName: "Roman Pizza",
    farAway: "7",
    businessAddress: "15 Atlas Rd, Kempton Park",
    images: require("../../assets/4.jpg"),
    averageReview: 4.3,
    numberOfReview: 700,
    coordinates: { lat: -26.1845336, lng: 28.2481691 },
    discount: null,
    deliveryTime: 20,
    collectTime: 10,
    foodType: "Chicken pizza, Vegetarian pizza...",
    productData: [
      {
        name: "Hand cut chips",
        price: 29.3,
        image: require("../../assets/4.jpg"),
      },
      { name: "Big Mac", price: 50.8, image: require("../../assets/4.jpg") },
      {
        name: "Chicken Burger",
        price: 70,
        image: require("../../assets/4.jpg"),
      },
    ],
    id: 3,
  },
];

export const productData = [
  {
    name: "Hand cut chips",
    price: 29.3,
    image: require("../../assets/5.jpg"),
    details: "Two 100% fresh beef burger patties that are hot, deliciously",
    id: 0,
  },
  {
    name: "Big Mac",
    price: 50.8,
    image: require("../../assets/5.jpg"),
    details: "McFeast features two 100% fresh beef burger patties that are hot",
    id: 1,
  },
  {
    name: "Chicken Burger",
    price: 70,
    image: require("../../assets/5.jpg"),
    details: "",
    id: 2,
  },
  {
    name: "Hand cut chips",
    price: 29.3,
    image: require("../../assets/5.jpg"),
    details: "Two 100% fresh beef burger patties that are hot, deliciously",
    id: 3,
  },
  {
    name: "Big Mac",
    price: 70.2,
    image: require("../../assets/5.jpg"),
    details: "McFeast features two 100% fresh beef burger patties that are hot",
    id: 4,
  },
  {
    name: "Chicken Burger",
    price: 70,
    image: require("../../assets/5.jpg"),
    details: "",
    id: 5,
  },
];
